export const faculties = [
    "Arts and Sciences",
    "Fine Arts",
    "Business Administration",
    "Architecture",
    "Engineering",
    "Health Sciences",
    "Medicine",
  ];
  export const departments = {
    "Arts and Sciences": [
      "American Culture and Literature",
      "Department of Matemathics",
      "Department of Molecular Biology and Genetics (English)",
      "Department of Psychology",
      "Department of Turkish Language and Literature",
      "Educational Sciences",
      "Psychology (English)",
      "Tarih Bilimleri",
      "Translation and Interpretation in English",
    ],
    "Fine Arts": [
      "Cartoon and Animation",
      "Department of Graphic Design",
      "Department of Textile and Fashion Design",
      "Digital Game Design",
      "Gastronomy and Culinary Arts",
      "Visual Communication Design",
    ],
    "Business Administration": [
      "Department of Business Administration (English)",
      "Department of Business Administration (Turkish)",
      "Department of Political Science and International Relations",
      "Department of Public Relations and Publicity",
      "Department of Tourism Management",
      "International Trade and Business (English)",
      "Management Information Systems (English)",
    ],
    Architecture: [
      "Department of Architecture",
      "Department of Interior Architecture",
      "Industrial Design",
    ],
    Engineering: [
      "Computer Engineering (English)",
      "Electrical and Electronics Engineering (English)",
      "Industrial Engineering (English)",
      "Mechanical Engineering (English)",
      "Software Engineering (English)",
    ],
    "Health Sciences": [
      "Midwifery",
      "Nursing",
      "Nursing (English)",
      "Nutrition and Dietetics",
      "Nutrition and Dietetics (English)",
      "Physiotheraphy and Rehabilitation",
      "Physiotherapy and Rehabilitation (English)",
    ],
    Medicine: ["Medicine", "Medicine (English)"],
  };